### ISSUE TITLE
Faucet link is broken

### ISSUE THREAD

**Issue by abitmore** [bitshares/how.bitshares.works#1]
On the [public testnet details page](https://github.com/bitshares/how.bitshares.works/blob/9596d0df7eb017f3b4c532d9d27060039fd6c1ed/developers/8_testnets/public_testnet_details.md), the faucet link is broken.

**Comment by cedar-book** [comment]
Updated: Faucet:  https://faucet.testnet.bitshares.eu/

**Comment by cedar-book** [comment]
how... and dev... both updated
