### ISSUE TITLE
Add a link to dev.bitshares.work

### ISSUE THREAD

**Issue by abitmore** [bitshares/how.bitshares.works#31]
Currently on https://how.bitshares.works/ site there is no link to https://dev.bitshares.works/, not good for developers to find docs.

**Comment by cedar-book** [comment]
I added the links here (http://how.bitshares.works/en/master/).  okay here or another better location?

**Comment by abitmore** [comment]
Where?

**Comment by abitmore** [comment]
Oh, saw them after refreshed the page. Good. Thanks.
